### PR TITLE
Customizable placeholder for the input field

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #31

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor deploy it please

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Pull request merged**
